### ISSUE TITLE
wrtc@0.0.9 install: `node bin/build.js` ERROR

### ISSUE THREAD

**Issue by mezzapp** [node-webrtc/node-webrtc#91] opened 2014-02-26 20:18 UTC
Debian Wheezy
Going to run the depot tools command: 
gclient sync -D --verbose -j1 in folder /node-webrtc/third_party/libwebrtc
.........................................................................................
For gclient sync -D --verbose -j1 something went wrong: error code 2, signal null.
??

**Comment by wouldgo** [comment] 2014-02-26 20:24
Have tried to run `node bin/build.js -v` (it should report that option when something goes wrong)?

**Comment by mezzapp** [comment] 2014-02-26 21:34
Thank you for suggestion. 
Get 
Error: Command download_from_google_storage --no_resume --platform=linux\* --no_auth --bucket chromium-gn -s trunk/tools/gn/bin/linux/gn.sha1 returned non-zero exit status 1 in /home/user/WEBRTC/node-webrtc/third_party/libwebrtc
/home/user/WEBRTC/node-webrtc/tools/depot_tools/third_party/boto/pyami/config.py:75: UserWarning: Unable to load AWS_CREDENTIAL_FILE ()
  warnings.warn('Unable to load AWS_CREDENTIAL_FILE (%s)' % full_path)
Failure: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed.

Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-gn -s trunk/tools/gn/bin/linux/gn.sha1' took 48.46 secs

gclient sync -D --verbose -j1 finished
For gclient sync -D --verbose -j1 something went wrong: error code 2, signal null.

**Comment by mezzapp** [comment] 2014-02-26 21:49
No more chance with    NPM INSTALL WRTC
node ./examples/bridges.js returns
/usr/local/lib/node_modules/wrtc/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file.

**Comment by modeswitch** [comment] 2014-02-26 23:32
Looks like the build was unsuccessful. Can you check for `webrtc.node` in the tree?

**Comment by DamonOehlman** [comment] 2014-02-28 23:14
I'm seeing build problems too, looks like ninja is failing:

```
gclient runhooks finished
Going to run the depot tools command: ninja -C trunk/out/Release in folder /home/doehlman/code/github/node-webrtc/third_party/libwebrtc
die: error: must run as rootlog: ninja version 0.1.3 initializing


ninja finished
For ninja something went wrong: error code 1, signal null.
    Try to run build script with --verbose option to find the possible problem.
```

Manual invocation of ninja in the `third_party/libwebrtc` folder behaves as expected though:

```
../../tools/depot_tools/ninja -C trunk/out/Release/
```

**Comment by wouldgo** [comment] 2014-03-01 11:24
Have you tried to remove the `depot_tools` folder and download again? I saw that error only once and I resolved with a fresh content download.
Furthermore yesterday I rebuilt the entire library w/o any problems, so It's quite a strange error...

**Comment by DamonOehlman** [comment] 2014-03-01 11:58
Just did a full removal of the `tools` and `third_party` folder and ran:

```
node bin/build.js --verbose
```

Same failure condition as before:

```
Generating gyp files from GN...
Updating projects from gyp files...

gclient runhooks finished
Going to run the depot tools command: ninja -C trunk/out/Release in folder /home/doehlman/code/github/node-webrtc/third_party/libwebrtc
die: error: must run as rootlog: ninja version 0.1.3 initializing

For ninja something went wrong: error code 1, signal null.
    Try to run build script with --verbose option to find the possible problem.
```

**Comment by wouldgo** [comment] 2014-03-01 12:32
To be sure I just done these steps:
- ran `node bin/clean.js`;
- ran `rm -Rf node_modules`;
- ran `npm install`.

and the build process ended w/o problems.
Dunno how to reproduce that behaviour.

**Comment by DamonOehlman** [comment] 2014-03-02 02:42
@wouldgo What platform are you building on?

**Comment by DamonOehlman** [comment] 2014-03-02 10:13
@wouldgo This seems to be related to having globally available versions of tools such as `ninja` when attempting to the build.  I think if the `gclient` and `ninja` executables were invoked using an absolute path then this might fix the problem...

**Comment by wouldgo** [comment] 2014-03-02 11:37
I build in a ubuntu 12.04 LTS. The fact of having globally available versions of `depot_tools` is resolved by the first line of the `build.js` script where I declare a new enviroment for the next execution and [this](https://github.com/js-platform/node-webrtc/blob/develop/bin/build.js#L22) line, where I append to `$PATH` the `depot_tools` folder that is populated during the first step of building process.

In this way commands like `gclient` and `ninja` are globally available in the building execution environment.

**Comment by DamonOehlman** [comment] 2014-03-02 12:35
The line you reference isn't exactly a bullet-proof way of locating the correct `gclient` or `ninja` executable,   It overrides the PATH and provides the depot_tools path in as the last lookup path in the `PATH` environment.  That said making it the first option would probably resolve the problems that I (and some others) are reporting.

I'd still go with the absolute path for execution (for robustness), but that's just the way I would do things...

**Comment by wouldgo** [comment] 2014-03-02 12:53
Thinking about what you typed I see only one possible issue: what happen if `depot_tools` are already in `$PATH`? If I remember well the first occurrence is resolved.

Probably it should be checked if there already are `gclient` and `ninja`. Is there anything else that I'm missing?

**Comment by modeswitch** [comment] 2014-03-02 14:15
I'm also having issues with the depot_tools in the project directory, after uninstalling the system version. Looks like this is broken.

**Comment by wouldgo** [comment] 2014-03-02 14:26
I haven't `depot_tools` system widely installed and yesterday I built again w/o issues. I'm trying now...

**Comment by modeswitch** [comment] 2014-03-02 14:30
```
Error: Command /home/ack/.virtualenvs/node-webrtc/bin/python trunk/webrtc/build/gyp_webrtc -Dextra_gyp_flag=0 returned non-zero exit status 1 in /home/ack/work/node-webrtc/third_party/libwebrtc
Generating gyp files from GN...
Updating projects from gyp files...
Traceback (most recent call last):
  File "trunk/webrtc/build/gyp_webrtc", line 80, in <module>
    sys.exit(gyp.main(args))
  File "/home/ack/work/node-webrtc/third_party/libwebrtc/trunk/tools/gyp/pylib/gyp/__init__.py", line 527, in main
    return gyp_main(args)
  File "/home/ack/work/node-webrtc/third_party/libwebrtc/trunk/tools/gyp/pylib/gyp/__init__.py", line 503, in gyp_main
    options.circular_check)
  File "/home/ack/work/node-webrtc/third_party/libwebrtc/trunk/tools/gyp/pylib/gyp/__init__.py", line 91, in Load
    generator = __import__(generator_name, globals(), locals(), generator_name)
ImportError: Import by filename is not supported.
```

**Comment by piranna** [comment] 2014-03-02 14:36
I bet we should use fixed versions of the tools, too... :-/

Send from my Samsung Galaxy Note II

**Comment by modeswitch** [comment] 2014-03-02 14:40
OK, I have this building now without local depot_tools installed. NPM package also updated. Please give this a try everyone and report back.

**Comment by wouldgo** [comment] 2014-03-02 14:41
So now I'm confused... Ran `node bin/clean.js`, then `rm -Rf node_modules` and `npm install`. After these steps ran `npm install` and It finishes smootly...

```
> wrtc@0.0.10 install /home/dario/git/node-webrtc
> node bin/build.js

Going to eventually download depot tools from https://chromium.googlesource.com/chromium/tools/depot_tools.git in /home/dario/git/node-webrtc/tools/depot_tools
.................................................................................................................................................................................
Going to run the depot tools command: gclient config http://webrtc.googlecode.com/svn/trunk in folder /home/dario/git/node-webrtc/third_party/libwebrtc 
.
Going to run the depot tools command: gclient sync -D --verbose -j1 in folder /home/dario/git/node-webrtc/third_party/libwebrtc
..................................................................................................................................................................................................................................................................................................
Going to run the depot tools command: gclient runhooks in folder /home/dario/git/node-webrtc/third_party/libwebrtc
.............
Going to run the depot tools command: ninja -C trunk/out/Release in folder /home/dario/git/node-webrtc/third_party/libwebrtc
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Going to run commnad: /home/dario/git/node-webrtc/node_modules/node-gyp/bin/node-gyp.js rebuild in folder /home/dario/git/node-webrtc
...........
wrtc module build complete
```

**Comment by DamonOehlman** [comment] 2014-03-02 21:31
@modeswitch I'll give the changes a try on my machine that has been complaining and let you know how it goes...

**Comment by DamonOehlman** [comment] 2014-03-02 23:44
@modeswitch The tweaks have fixed the build on a machine that was previously giving me trouble.

@wouldgo Yes this is the change that we talked about, Alan simply pushed the `depot_tools` path to the front of the `PATH` environment variable, meaning it became the first resolved when either `gclient` or `ninja` was executed.

**Comment by wouldgo** [comment] 2014-03-03 07:15
@DamonOehlman good :)

**Comment by mezzapp** [comment] 2014-03-03 17:16
For information, it works for me after these checks 
1 - follow the instructions concerning your PATH at
https://sites.google.com/a/chromium.org/dev/developers/how-tos/install-depot-tools
2 - check your SYSTEM DATE (this for npm error "cannot run in wd ....")
3 - run the errored scripts manually with --verbose option (these using google depot tools)

**Comment by jcrubino** [comment] 2014-04-07 05:37
problem persisting for wrtc@0.0.12  Ubuntu 64 12.04

```
6856 info postuninstall wrtc@0.0.12
6857 error wrtc@0.0.12 install: `node bin/build.js`
6857 error Exit status 1
6858 error Failed at the wrtc@0.0.12 install script.
6858 error This is most likely a problem with the wrtc package,
6858 error not with npm itself.
6858 error Tell the author that this fails on your system:
6858 error     node bin/build.js
6858 error You can get their info via:
6858 error     npm owner ls wrtc
6858 error There is likely additional logging output above.
6859 error System Linux 3.8.0-37-generic
6860 error command "/usr/bin/node" "/usr/bin/npm" "install" "wrtc"
6861 error cwd /home/main/Development/Apps/tmp
6862 error node -v v0.10.26
6863 error npm -v 1.4.3
6864 error code ELIFECYCLE
6865 verbose exit [ 1, true ]
```

**Comment by modeswitch** [comment] 2014-04-25 17:19
Please retry with 0.0.18.

**Closed as completed by modeswitch** 2014-04-25 17:19 UTC
