### ISSUE TITLE
Sending audio stream over PeerConnection or over a DataChannel?

### ISSUE THREAD

**Issue by lresc** [node-webrtc/node-webrtc#159] opened 2015-01-16 19:23 UTC
Hi!

I want to send audio stream from browser to nodejs. 
My question is, should I do over PeerConnection or over a DataChannel?
I've seen that MediaStream is disabled.

Thank you!

**Comment by modeswitch** [comment] 2015-01-17 00:48
Your only option here is to use a data channel.

**Comment by modeswitch** [comment] 2015-02-10 01:05
Duplicate of #156.

**Closed as completed by modeswitch** 2015-02-10 01:05 UTC
Labels: duplicate
