### ISSUE TITLE
Prebuilt binaries

### ISSUE THREAD

**Issue by guymguym** [node-webrtc/node-webrtc#168] opened 2015-03-01 15:57 UTC
Hi

Great project!

I think it would be even more usable if it would provide prebuilt binaries.

Build from source takes a long time and as such is less attractive to embed in existing projects.

I think this also helped node-webkit (https://github.com/nwjs/nw.js) gain popularity - if I had to build it from source in every project it would be a real pain.

What do you think?

**Comment by modeswitch** [comment] 2015-03-03 00:30
Yeah, I will investigate compiled binaries for some common platforms.

**Comment by piedshag** [comment] 2015-03-27 09:02
@modeswitch I have placed a 15 dollar bounty on this issue. I hope it is of assistance.

**Comment by modeswitch** [comment] 2015-03-27 18:01
@fbodz I don't understand what you mean. Is this a Github feature?

**Comment by rosskukulinski** [comment] 2015-03-27 20:29
@guymguym AND @fbodz -- do you have any preferences on initial binaries to support?  I was thinking OSX & Ubuntu x86_64

**Comment by piedshag** [comment] 2015-03-27 20:34
@modeswitch There is a service called bountysource which allows you to place bounties on Github issues. Here is the url https://www.bountysource.com/issues/9082012-prebuilt-binaries. @rosskukulinski  I think OSX and Ubuntu x86_64 would be a great start. Thanks. Let the race begin!

**Comment by rosskukulinski** [comment] 2015-03-27 22:29
Working on a fork with automated pre-compiled binaries.

**Comment by piedshag** [comment] 2015-03-27 22:32
@rosskukulinski Have you logged in as a developer on bounty source. Therefore i can release the bounty when the fork is merged.

**Comment by guymguym** [comment] 2015-03-27 22:33
I am eventually interested in Windows, but this is still an open issue #42.
OSX is a good start as well.
:+1:

**Comment by rosskukulinski** [comment] 2015-03-27 22:38
@fbodz I'll gladly accept the bounty and then donate to charity.  I'm more interested in speeding up our own build->test->deploy process.

**Comment by piedshag** [comment] 2015-03-27 22:41
@rosskukulinski Sounds great. When the prebuilt binaries are released and the issue is closed. I will be more than happy to release the bounty. Do you have any idea when you think the binaries will be completed.

**Comment by rosskukulinski** [comment] 2015-03-30 19:01
@modeswitch - the test for this will be to verify that the next time you tag a new version and push -- does the automated build work correctly.

**Comment by modeswitch** [comment] 2015-03-30 19:28
@rosskukulinski I'll publish when I have a sec.

FWIW, I was using node-pre-gyp before but it was more trouble that it was worth.

**Comment by rosskukulinski** [comment] 2015-03-30 19:29
Well hopefully I haven't made things worse :-/.  "Works on my machine" :)

**Comment by modeswitch** [comment] 2015-03-30 19:35
@rosskukulinski Yeah, that's one of the issues. Some of the library dependencies are linked dynamically at runtime, which means the pre-built binaries are distro-specific. That can cause unexpected failures.

**Comment by modeswitch** [comment] 2015-03-30 19:41
@rosskukulinski published

**Comment by modeswitch** [comment] 2015-03-30 19:42
@rosskukulinski The module is still building from source for some reason.

**Comment by modeswitch** [comment] 2015-03-30 19:45
@rosskukulinski Oh, that's probably because there isn't an up-to-date binary version. If you republish the binary builds this should work.

**Comment by rosskukulinski** [comment] 2015-03-30 19:58
@modeswitch can you push a new git tag?  The build scripts look for git tags or the string '[publish binary]" in a commit.

**Comment by rosskukulinski** [comment] 2015-03-30 20:03
OSX binary has been built & published for 0.0.50
https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.50/Release/node-v11-darwin-x64.tar.gz

**Comment by modeswitch** [comment] 2015-03-30 20:15
@rosskukulinski Tagged as v0.0.50.

**Comment by rosskukulinski** [comment] 2015-03-30 20:19
Thanks.  I'll keep an eye on the [build](https://travis-ci.org/js-platform/node-webrtc/builds/56469741) and report back what happens.

**Comment by rosskukulinski** [comment] 2015-03-30 20:27
blah -- it failed.  I wonder why the credentials are missing...

```
node-pre-gyp ERR! stack TimeoutError: Missing credentials in config
node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/home/travis/build/js-platform/node-webrtc/node_modules/aws-sdk/lib/http/node.js:56:34)
node-pre-gyp ERR! stack     at ClientRequest.g (events.js:180:16)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:92:17)
node-pre-gyp ERR! stack     at Socket.emitTimeout (http.js:1798:10)
node-pre-gyp ERR! stack     at Socket.g (events.js:180:16)
node-pre-gyp ERR! stack     at Socket.emit (events.js:92:17)
node-pre-gyp ERR! stack     at Socket._onTimeout (net.js:327:8)
node-pre-gyp ERR! stack     at _makeTimerTimeout (timers.js:429:11)
node-pre-gyp ERR! stack     at Timer.unrefTimeout [as ontimeout] (timers.js:493:5)
node-pre-gyp ERR! System Linux 2.6.32-042stab090.5
node-pre-gyp ERR! command "node" "/home/travis/build/js-platform/node-webrtc/node_modules/.bin/node-pre-gyp" "package" "publish"
node-pre-gyp ERR! cwd /home/travis/build/js-platform/node-webrtc
node-pre-gyp ERR! node -v v0.10.38
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
```

**Comment by rosskukulinski** [comment] 2015-03-30 20:36
ahh -- the .travis.yml encrypted tokens are tied to the owner/repo and do not work for forks.  I created those files based on yodlr/node-webrtc rather than js-platform/node-webrtc, which is why it worked for my fork, but not the main repo.  I'll generate new secure tokens for js-platform/node-webrtc and submit a PR.

**Comment by rosskukulinski** [comment] 2015-03-30 20:36
For reference: http://docs.travis-ci.com/user/encryption-keys/

**Comment by modeswitch** [comment] 2015-03-30 20:46
@rosskukulinski Can you document this process?

**Comment by rosskukulinski** [comment] 2015-03-30 20:51
Sure thing, @modeswitch.  I can also send you the S3 credentials that I'm using.  For now, I've volunteered [yodlr](https://getyodlr.com)'s S3 account for storing binaries.  If you'd prefer to own the storage facility, that's fine with me.

**Comment by rosskukulinski** [comment] 2015-03-30 21:00
woo!  Auth keys are correct now.  Another version bump should properly build the Linux binaries automatically.

https://travis-ci.org/js-platform/node-webrtc/jobs/56474699
![screen shot 2015-03-30 at 2 00 21 pm](https://cloud.githubusercontent.com/assets/2746479/6906667/255f853a-d6e5-11e4-9c08-5200a9e3324b.png)

**Comment by rosskukulinski** [comment] 2015-03-31 22:25
ok @modeswitch - linux builds were done automatically for 0.0.51:

wrtc/v0.0.51/Release/node-v0.11.16-linux-x64.tar.gz
wrtc/v0.0.51/Release/node-v11-linux-x64.tar.gz.

I think this issue can be closed.  I still need to writeup documentation per #176

**Comment by modeswitch** [comment] 2015-03-31 22:27
@rosskukulinski Did you add yourself to the contributors list? If not, please make another pull request to do that (only of you want).

**Comment by rosskukulinski** [comment] 2015-03-31 22:29
@modeswitch done in #181.  Thanks

**Comment by modeswitch** [comment] 2015-03-31 22:30
@rosskukulinski One potential issue here is that OSX builds will not be done automatically, so on that platform the installer may fall back to building from source intermittently.

**Comment by rosskukulinski** [comment] 2015-03-31 22:32
@modeswitch yep, if we harass travis we can have automated osx builds.  Until then I plan on manually publishing OSX binaries for each tagged version.

**Comment by hackwaly** [comment] 2015-04-01 11:20
Great!
Which node version is node-v11? Current latest stable node version is 0.12.
I got message when I install wrtc:

```
 Pre-built binary not available for your system, looked for https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.51/Release/node-v14-linux-x64.tar.gz (falling back to source compile with node-gyp) 
```

**Comment by rosskukulinski** [comment] 2015-04-01 16:24
@hackwaly I have not setup prebuilt for 0.12, mostly because it seems we have a segfault in 0.12: #164.

I just built & ran tests against 0.12 and the tests _did_ pass.  I've pushed changes to my fork to enable automated builds on 0.12 and I'll see what happens with Travis.  If you're curious about following along:

https://travis-ci.org/yodlr/node-webrtc/builds/56746299

If the build passes, I'll open a PR to add 0.12 automated builds.

**Closed as completed by rosskukulinski** 2015-04-01 16:24 UTC
Labels: enhancement

**Comment by modeswitch** [comment] 2015-04-01 16:37
@rosskukulinski I updated NaN to 1.7.0, which fixed a few issues I was seeing.

**Comment by max-mapper** [comment] 2015-04-06 03:19
@rosskukulinski i installed wrtc just now on `iojs` but it didn't grab a prebuilt. it fell back to compilation. are `iojs` prebuilt binaries supported?

**Comment by modeswitch** [comment] 2015-04-06 03:57
@maxogden It's probably failing to match the version string. We probably need to add `iojs` to the node versions we test against, which will trigger `iojs` builds.

**Comment by modeswitch** [comment] 2015-04-06 03:59
@maxogden Opened #187 for this.
