### ISSUE TITLE
PeerConnection constructor should read and honor options and media constraints

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#37] opened 2013-12-20 19:43 UTC
These things are hard-coded right now.

**Comment by markandrus** [comment] 2018-03-29 18:30
This was landed recently and is coming in 0.1.0.

**Closed as completed by markandrus** 2018-03-29 18:30 UTC
Labels: bug, critical, interop

**Comment by McPo** [comment] 2018-04-18 13:58
Does this mean the following would now be supported.

```
const pc = new RTCPeerConnection({
    iceServers: [
        ....
    ]
}, {
    mandatory: [
        { DtlsSrtpKeyAgreement: false }
    ]
});
```

I notice that `DtlsSrtpKeyAgreement`  is used in
https://github.com/js-platform/node-webrtc/blob/911c9a8057f8dba88ba21fd8aead4c6aaf834b84/examples/bridge.js#L141

However I have been using @thedracle fork and it does not appear to be honoured. I then attempted to use the latest official version of wrtc but was unable to get past creation of an offer (It never resolved), in order to inspect the SDP. Looking for `a=crypto` as opposed to `a=fingerprint`, to prove that SDES is being used.

Cheers,
Emmet

**Comment by markandrus** [comment] 2018-04-19 00:35
Hi @McPo,

No, the second argument is non-standard and unsupported. I think it may have been supported in early versions of Chrome, but, looking at the earliest node-webrtc tags, I don't think either argument to RTCPeerConnection was ever honored in the library. Check out the [CHANGELOG.md](https://github.com/js-platform/node-webrtc/blob/v0.1.3/CHANGELOG.md#rtcconfiguration) entry for the RTCConfiguration addition to see the options we now support.

> I then attempted to use the latest official version of wrtc but was unable to get past creation of an offer (It never resolved), 

This is concerning. Mind opening a separate issue with a minimal repro?

> Looking for `a=crypto` as opposed to `a=fingerprint`, to prove that SDES is being used.

Yes, that'd indicate it. Do you want/need SDES support? I expect it'll be removed soon if it hasn't already been removed from the more recent versions of WebRTC we plan to upgrade to.

Mark

**Comment by McPo** [comment] 2018-06-14 11:53
Hey @markandrus, thanks for the quick response, sorry for the long delay in getting back to you.

I just got a bit of time and manage to implement the `DtlsSrtpKeyAgreement` parameter (Was easier than I expected), and submitted a PR to the thedracle fork  https://github.com/thedracle/node-webrtc/pull/3. 

Regarding:
> I then attempted to use the latest official version of wrtc but was unable to get past creation of an offer (It never resolved)

Im no longer having the issue. I suspect It might have been caused by attempting to use node-webrtc for audio, which the main project didn't support. Basically user error.
