### ISSUE TITLE
raspberry pi 3/ arm7

### ISSUE THREAD

**Issue by temaivanoff** [node-webrtc/node-webrtc#388] opened 2018-04-12 15:52 UTC
Hi, does anyone have an instruction how to build raspberry pi 3/ arm7 ? any help Thanks

**Comment by nazar-pc** [comment] 2018-04-13 11:41
Seems to generally duplicate #367 despite not Android

**Comment by alessiopcc** [comment] 2018-04-27 19:11
I use this module on a Raspberry pi 3.
Cross-compile Webrtc M60 for Linux arm and build this module on the Raspberry.
To build it: create a `third_party` folder, put library and headers into it and run the `install` script.

This is the archive with the cross-compiled library and headers that I've manually built (if you want to try): [webrtc.tar.gz](https://github.com/js-platform/node-webrtc/files/1956097/webrtc.tar.gz)

As soon as I've time I'll try to include the cross-compilation in [libwebrtc](https://github.com/aisouard/libwebrtc)

**Comment by markandrus** [comment] 2018-04-27 19:14
@alessiopcc if you can do that, I'd be happy to support Raspberry Pi 3. Building WebRTC and hosting binaries for a variety of platforms is really the biggest challenge with this project and the reason we don't support this platform already. Otherwise, cross-compiling in Travis CI should be straightforward assuming we can pull down libwebrtc for the appropriate architecture(s).

**Comment by temaivanoff** [comment] 2018-04-27 19:29
@alessiopcc 
Hi, i found this project https://github.com/keroserene/go-webrtc
There are static library and headers `webrtc 64`.

**Comment by alessiopcc** [comment] 2018-04-28 01:30
@fast0490f  Node.js bindings are for version 60 so I don't think the library from the go bindings will work.

@markandrus Yeah, I know the problem.

**Comment by temaivanoff** [comment] 2018-04-28 04:54
@markandrus @alessiopcc
I do not quite understand what is the latest version of the library itself and what version is used in node-webrtc. what a mess with versions, can you explain to me please

M66 - https://webrtc.org/release-notes/
1.1 - https://en.m.wikipedia.org/wiki/WebRTC
1.3 - https://github.com/js-platform/node-webrtc/releases

**Comment by nazar-pc** [comment] 2018-04-28 10:26
M66 - version of underlying implementation of WebRTC in Chromium used by node-webrtc
1.1 - version of the WebRTC specification/standard
0.1.3 - version of node-webrtc module for Node.js

These are different versions of different things.

node-webrtc can use specific version of libwebrtc that is based on Mxx version of Chromium's implementation that implements some version of the specification. They don't necessary follow the same versioning scheme.

**Comment by temaivanoff** [comment] 2018-04-28 10:50
@nazar-pc 
Thank you very much for the explanation. Correctly I understand that `node-webrtc` 0.1.3 uses `M60` - https://github.com/mayeut/libwebrtc/releases/tag/v1.1.1

![image](https://user-images.githubusercontent.com/11176223/39395739-061be2e0-4aeb-11e8-9e43-d9e26981f9df.png)

**Comment by nazar-pc** [comment] 2018-04-28 11:59
@fast0490f, yes

**Comment by Stupid-Git** [comment] 2018-05-02 16:45
@alessiopcc Thanks for the archived lib and include files. Many of us, myself included, have tried to cross compile libwebrtc.a and failed. Although an addition of an Arm build within the [libwebrtc](https://github.com/aisouard/libwebrtc) project would be most welcome, I would dearly appreciate it you could provide us with a history dump for the cross-compile procedure  and what OS version you were using. Thanks.

**Comment by alessiopcc** [comment] 2018-05-15 23:48
Those are the arguments I've used for the `gn gen` command:
```
use_gold = false
target_cpu = "arm"
target_os = "linux"
is_component_build = false
is_debug = false
rtc_include_tests = false
```

**Comment by willmtemple** [comment] 2018-07-19 19:20
@markandrus any update on this? I'm attempting to build for ARMv6 and ARMv8 devices (Raspberry Pi 0 W and Raspberry Pi 3 B+)

I can build the master tree of webrtc with:

`gn gen out/Default --args='target_cpu="arm" target_os="linux" arm_float_abi="hard" arm_version=6 arm_use_neon=false arm_optionally_use_neon=false arm_arch="armv6" arm_fpu="vfp"'; ninja -C out/Default`, using the repo provided by Google, but in the M60 tree, compilation chokes on BoringSSL, which apparently uses instructions that aren't supported on ARMv6.

I can build the library for armv7 with the options provided by @alessiopcc, but the linker fails to link the objects together. Is there a way to build node-webrtc against the master branch of webrtc? I imagine to do that I'd have to hack on API changes since M60?

**Comment by markandrus** [comment] 2018-07-19 20:13
I am not working in this, but I will accept PRs. To get this supported, we need a PR against libwebrtc adding ARM support and Travis CI support for building and publishing WebRTC binaries for ARM. Then we need a PR to this repo adding Travis CI support for building for ARM using the newly published binaries.

**Comment by willmtemple** [comment] 2018-07-24 00:11
@markandrus I'm working on this. Currently the issue is that the version of BoringSSL vendored with webrtc 60 simply does not build for armv6, since some of its assembly fragments use unsupported instructions. This repo will have to be ported forward to a new version of webrtc to support arm6.

(Side note, something that confuses me: does this repo depend on mayeut/libwebrtc or aisouard/libwebrtc? It looks like these repos haven't been touched in about a year. I can probably add support to build ARM libraries to one of those relatively quickly, but what I don't know is where those binaries should be published. IMO, it would make sense if aisouard/libwebrtc was forked here and build artifacts published to releases in this github org.)

I can build wrtc.node for armv7-a, but this will neglect many good targets like the (incredibly cheap) Pi 0. I can build webrtc release 67 for armv6, but there is apparently some significant hacking that will be required to port wrtc.node to webrtc 67.

**Comment by markandrus** [comment] 2018-07-24 01:19
@willmtemple 

> This repo will have to be ported forward to a new version of webrtc to support arm6.

I've been working on this. Actually, the changes necessary for M68 are here: https://github.com/js-platform/node-webrtc/pull/420 — I have some problems building on Linux, though (getting strange segfaults for certain versions of Node), and there's an apparent header issue on Windows I need to fix. macOS seems to work OK, though.

> (Side note, something that confuses me: does this repo depend on mayeut/libwebrtc or aisouard/libwebrtc? It looks like these repos haven't been touched in about a year.

[v0.0.63](https://github.com/js-platform/node-webrtc/releases/tag/v0.0.63) was the first release to use aisouard/libwebrtc's release at M57, and [v0.1.0](https://github.com/js-platform/node-webrtc/releases/tag/v0.1.0) updated to mayeut/libwebrtc at M60. I'd like v0.2.0 to move to M68 or newer, so I've been trying to get M68 working over at markandrus/libwebrtc.

> I can probably add support to build ARM libraries to one of those relatively quickly

This would be awesome! Actually, if you can spot where I'm going wrong on Linux, that'd be awesome. Things to keep in mind, though: what compiler will we use? clang or gcc? What standard library? I've been rediscovering API/ABI issues trying to get M68 to work.

> but what I don't know is where those binaries should be published.

If your changes are accepted on aisouard/libwebrtc and he releases new binaries, I think that'd be ideal. I don't really like maintaining them. We could also revisit depending on libwebrtc binaries at all. Build times are more reasonable these days (~30 min), so building node-webrtc binaries from source on Travis CI and Appveyor would be slower but doable.

> IMO, it would make sense if aisouard/libwebrtc was forked here and build artifacts published to releases in this github org.)

Yes, this is an option. I don't have permission on js-platform right now. I'd need to request it from @modeswitch if we go this route.

> I can build wrtc.node for armv7-a, but this will neglect many good targets like the (incredibly cheap) Pi 0. I can build webrtc release 67 for armv6, but there is apparently some significant hacking that will be required to port wrtc.node to webrtc 67.

If you're up for it, please try my M68 changes?

Thanks!
Mark

**Comment by willmtemple** [comment] 2018-07-24 03:39
> changes necessary for M68 are here: #420 — I have some problems building on Linux, though

Oh, that's _great_ news, as I am not a C++ developer. I'll take a look at the patch and try to get some builds for Linux going.

> what compiler will we use? clang or gcc?

I'm using clang on my system for now. If js-platform owns the CI pipeline for wrtc.node AND libwebrtc.a, then we can use the same clang for both and we can just use whatever libstdc++.so google bundled with the sysroot for libwebrtc.a. That would positively ensure ABI compatibility if they are both built together.

**Comment by thehans** [comment] 2018-07-29 16:39
Hello I could use some help compiling node-webrtc for Raspberry Pi 3, to run on latest raspbian stretch images.

I found some RPi3 on specific instructions for building WebRTC, and I was able to complete this (substituting M60) without error, but I guess this is different from the libwebrtc in that it doesn't output a single static lib?
https://github.com/ipop-project/ipop-project.github.io/wiki/Build-WebRTC-Libraries-for-Raspberry-Pi-3-(Cross-compile-on-Ubuntu)

Is it possible to build node-webrtc based on the webrtc build instructions from that link?

The section of the node-webrtc instructions to copy over output folders of course doesn't have corresponding paths:
```
cp -r <path of libwebrtc>/out/lib third_party/webrtc
cp -r <path of libwebrtc>/out/include third_party/webrtc
```

Other instructions I've attempted for building libwebrtc seem to fail to find sysroot, and additionally are looking for a jessie sysroot, which I assume would not be compatible with a stretch based OS.

It doesn't help that I'm not familiar with any of this google suite of build tools at all, or why it needs 20GB of dependencies to build this one library.

**Comment by ghost** [comment] 2018-11-22 18:57
Hi all,
I am trying to compile wrtc v0.3.2 for arm/raspberry pi.
Actually I can compile webrtc for arm (M70) completely & can produce libwebrtc.a binary.

As I see wrtc needs libc++_objects like (algorithm.o, any.o etc..) (CMakeLists.txt)
But the problem is that if you compile webrtc for arm then webrtc does not produce this objects.
@markandrus do you have any idea about that?

In previous versions there was an option to provide webrtc binary files to wrtc but in this version there is not.

Any idea or workaround about that?
Or any successful wrtc v0.3.2 compilation for arm/raspberry pi?
Thanks

**Comment by markandrus** [comment] 2018-11-22 19:06
Hi @doganmurat,

My hope with the updated CMakeLists.txt is that cross-compilation for ARM may be easier and that we could add support in Travis/Circle CI for it. I haven’t looked into this yet, though. Did you add to CMakeLists.txt to compile for ARM? Could you share those initial changes? If you do, it’s be easier for me to check what next we need to do.

Best,
Mark

**Comment by ghost** [comment] 2018-11-23 11:45
Hi @markandrus ,

I made a successful cross-compile for ARM.
I created a pull request with all necessary modifications.
Please check it!

Murat

**Comment by willmtemple** [comment] 2018-11-27 22:32
@doganmurat What was the resolution to requiring the C++ objects (algorithm.o, etc.)? When I try to compile with the instructions in the readme, I have missing objects:

```
Running ncmake configure
-- NodeJS: Using node, version v8.12.0
-- Configuring done
-- Generating done
-- Build files have been written to: .../Development/node-webrtc/build
Running ncmake build
ninja: error: 'external/libwebrtc/build/Release/obj/buildtools/third_party/libc++/libc++/algorithm.o', needed by 'Release/wrtc.node', missing and no known rule to make it
Build failed
.../node-webrtc/scripts/install.js:52
    throw new Error('ncmake build failed for wrtc');
    ^
```

**Comment by ghost** [comment] 2018-11-28 04:11
Hi
Please use dev branch, it will solve your problems.
All necessary steps already committed.
Check CMakeLists.txt

Regards
Murat

**Comment by markandrus** [comment] 2018-12-16 01:21
Hi y'all, thanks to @doganmurat and @zsmweb's contributions, we now ship armv7l and arm64 binaries, as of [v0.3.3](https://github.com/node-webrtc/node-webrtc/releases/tag/v0.3.3). They're only tested with QEMU in CircleCI, so if you could, please test the pre-built binaries on a real device.

**Comment by webarchymeta** [comment] 2018-12-16 22:25
I have tested the new version (v0.3.3) on several of our arm64 SBCs (nanopi M4, neo2, raspbarry pi B 3), they all work as expected so far

**Comment by nazar-pc** [comment] 2018-12-23 20:43
I've just tested in VM with `virt` ARMv7 architecture from QEMU - installed prebuilt binary without issues, maybe this can be closed now?

**Closed as completed** 2018-12-23 20:54 UTC

**Comment by chr15m** [comment] 2018-12-24 17:08
Is this expected to work on Android? I tried to install it under Termux on Android:

```
$ node --version
v8.11.3
```

```
$ npm i wrtc

> wrtc@0.3.3 install /data/data/com.termux/files/home/node_modules/wrtc
> node scripts/install.js

Searching for a pre-built wrtc binary
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.3.3/Release/node-v57-android-arm64.tar.gz
```

Is there some way for me to force it to use pre-built `wrtc/v0.3.4-dev/Release/node-v57-linux-arm64.tar.gz` instead?

**Comment by nazar-pc** [comment] 2018-12-24 17:42
@chr15m I was using Node.js v10 LTS on armhf (32-bit)

**Comment by markandrus** [comment] 2018-12-24 22:50
@chr15m, I don’t think it will work on Android. We need a different build configuration for that, AFAIK. We’re building Linux only right now.

**Comment by chr15m** [comment] 2018-12-29 21:40
@markandrus Android is an ARM/Linux platform which is why I thought it might work. If I can figure out how force `node-gyp-prebuilt` to use the `linux-arm64` build I can see if it works there. Will report back here if I manage to get anything working.

**Comment by markandrus** [comment] 2018-12-30 00:38
@chr15m OK, please give it a try. I'm not sure it will work, though, because `node-pre-gyp` is going to use the [`process.platform` string](https://nodejs.org/api/process.html#process_process_platform) ("android" for [experimental Android builds](https://github.com/nodejs/node/blob/master/BUILDING.md#androidandroid-based-devices-eg-firefox-os), "linux" for Linux builds) to look up the pre-compiled binary. There may be some incompatibility between the Linux build and what Android requires.

**Comment by temaivanoff** [comment] 2019-02-13 21:38
@chr15m, @nazar-pc 
You can confirm the successful launch in manual mode on termux?

termux: npm i wrtc
Еrror: Unable to find native module

**Comment by nazar-pc** [comment] 2019-02-13 21:58
What is different about termux? Works for me on armhf both in QEMU and on Raspberry PI 3 B+. Though I'm using Docker container on RPI (both `arm32v7/node:10` and `arm32v7/ubuntu:18.04` with Node.js installed from `deb.nodesource.com`).

**Comment by temaivanoff** [comment] 2019-02-18 16:35
@nazar-pc 
Raspberry good work, not problem. While i'm not familiar with termux. As they claim it is a Linux environment
https://github.com/termux/termux-app

Android (temux) `uname -a`
`Linux localhost 4.4.153-perf+ #1 SMP PREEMPT Tue Jan 15 18:34:25 WIB 2019 aarch64 Android`

**Comment by temaivanoff** [comment] 2019-02-18 16:38
@markandrus 
I changed .node to linux_arm64. There is what any ideas ?

```js
internal/modules/cjs/loader.js:775
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen failed: library "libpthread.so.0" not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:775:18)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by nazar-pc** [comment] 2019-02-18 17:28
Android is Linux, but still quite a special one. I guess it will either require special build or static binary or something line that in order to work unfortunately.
