### ISSUE TITLE
got an error when call  await setLocalDescription();

### ISSUE THREAD

**Issue by RajanZhan** [node-webrtc/node-webrtc#735] opened 2022-09-17 15:28 UTC
as the title ,it was got an error when i call pc.setLocalDescription();  
the error as follow:
 var promise = this._pc.setLocalDescription(description);
                         ^
TypeError: Expected an object
    at RTCPeerConnection.setLocalDescription

please help me ,thinks to everyone!

**Comment by duvallj** [comment] 2024-05-02 13:55
Duplicate of https://github.com/node-webrtc/node-webrtc/issues/677

**Closed as completed by duvallj** 2024-05-02 13:55 UTC
