### ISSUE TITLE
negotiationneeded event is fired in invalid signalingState

### ISSUE THREAD

**Issue by sb-junhyeong** [node-webrtc/node-webrtc#586] opened 2019-12-13 12:28 UTC
According to [https://w3c.github.io/webrtc-pc/#dfn-update-the-negotiation-needed-flag](https://w3c.github.io/webrtc-pc/#dfn-update-the-negotiation-needed-flag), `negotiationneeded` event shouldn't be fired when `signalingState` is not `stable`.

By receiving `offer`, setting it with `localDescription` and then calling `addTrack`, you can check `negotiationneeded` is fired even when `signalingState` is `have-remote-offer`.

I checked google webrtc native source and it seems it fires `negotiationneeded` event whenever `direction` property of `RtpTransceiver`, which does not comply with  [https://w3c.github.io/webrtc-pc/#dfn-update-the-negotiation-needed-flag](https://w3c.github.io/webrtc-pc/#dfn-update-the-negotiation-needed-flag), 
AddTrack part of [https://w3c.github.io/webrtc-pc/#rtcpeerconnection-interface-extensions](https://w3c.github.io/webrtc-pc/#rtcpeerconnection-interface-extensions)

**Comment by markandrus** [comment] 2020-01-11 11:36
We may need to wait for Chrome/webrc.org to fix its implementation first, rather than try to work around it ourselves.

**Comment by fippo** [comment] 2020-01-11 13:30
this should be fixed these days, no? tagging @henbos @guidou

**Comment by henbos** [comment] 2020-01-13 09:18
The implementation of onnegotiationneeded that was fixed was the default sdpSemantics (Unified Plan) one, not the Plan B one.

In Unified Plan, we do make sure not to fire if signalingState is not stable ([code](https://source.chromium.org/chromium/chromium/src/+/master:third_party/webrtc/pc/peer_connection.cc;l=7374?q=peer_connection.cc&originalUrl=https:%2F%2Fcs.chromium.org%2F)). So I think this should work as intended. However, I do also know that the surfacing of firing these events to JavaScript involves some thread jumping and queuing of microtasks, so it's not inconceivable that there could be a bug if the signaling state is changing around the same time that we want to fire an event, but I'd like to see repro steps for that.

File a https://crbug.com bug if you find an issue with negotiationneeded in Unified Plan.

**Comment by henbos** [comment] 2020-01-13 09:19
In Plan B though onnegotiationneeded fires all the time in non-compliant ways and is totally unreliable.

**Comment by sb-junhyeong** [comment] 2020-01-13 10:06
It occured in 0.4.2. Problem seems to be resolved after I updated to 0.4.3. In all those version I used `unified-plan`

**Comment by markandrus** [comment] 2020-01-19 18:05
Thanks, y'all. I rechecked the `RTCPeerConnection-onnegotiationneeded.html` WPT test, which was previously marked "flaky", and validated that it passes with 0.4.3 (based on M79).

**Closed as completed by markandrus** 2020-01-19 18:05 UTC
