### ISSUE TITLE
Installation Error on Mac Apple Silicon M1 (ARM)

### ISSUE THREAD

**Issue by ghost** [node-webrtc/node-webrtc#698] opened 2021-06-05 11:12 UTC
```
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/darwin-arm64.tar.gz
node-pre-gyp ERR! stack     at PassThrough.<anonymous> (/Users/test/Desktop/project/server/node_modules/node-pre-gyp/lib/install.js:149:27)
node-pre-gyp ERR! stack     at PassThrough.emit (events.js:388:22)
node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/Users/test/Desktop/project/server/node_modules/needle/lib/needle.js:508:9)
node-pre-gyp ERR! stack     at Object.onceWrapper (events.js:483:26)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:376:20)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:515:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:376:20)
node-pre-gyp ERR! stack     at addChunk (internal/streams/readable.js:309:12)
node-pre-gyp ERR! System Darwin 20.4.0
node-pre-gyp ERR! command "/opt/homebrew/Cellar/node@14/14.17.0/bin/node" "/Users/test/Desktop/project/server/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /Users/test/Desktop/project/server/node_modules/wrtc
node-pre-gyp ERR! node -v v14.17.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/darwin-arm64.tar.gz
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wrtc@0.4.7 install: `node scripts/download-prebuilt.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/test/.npm/_logs/2021-06-05T11_11_33_217Z-debug.log
test@testui-MacBookAir server % 
```

**Comment by ghost** [comment] 2021-06-05 11:16
I replaced my old macbook with an M1 macbook and encountered a problem while installing.

I tried to solve the problem by referring to several docs, but to no avail.

I checked that there is a document related to m1 in the Github issue, 
and tried to install it with a mac using an intel cpu in case of any problem, 
but it was installed without any problem.

I haven't found any other solutions, but I hope this helps you too.

**Comment by esarthou** [comment] 2021-06-14 21:19
+1

**Comment by draeder** [comment] 2021-07-13 01:52
This seems to be a universal issue. See #703, #693, #695, potentially #676.

**Comment by DiegoRBaquero** [comment] 2021-07-13 15:03
Use rosetta emulation

**Comment by sragvivadali** [comment] 2021-07-22 04:25
Yah, I am having that same error.

**Comment by azabrodin** [comment] 2021-08-10 21:26
Hi Guys some one find solutions ? HELP!!!

**Comment by azabrodin** [comment] 2021-08-10 21:29
Have same problem with wrtc install, I tied install node-pre-gyp, but doesn't work.

**Comment by tyohan** [comment] 2021-10-13 02:38
Following the [guideline here ](https://www.jurnalanas.com/node-js-mac-m1/) i managed to install this on Macbook Air M1. I'm using [NVM](https://github.com/nvm-sh/nvm) to install my node. 

1. Open terminal
2. switch to x64 arch `arch -x86_64 zsh`, change `zsh` with your own shell
3. make sure you run in x64 arch by run `node -p process.arch` it must be output `x64` if everything correct
4. Install node in x65 version `nvm install v14.15.4`, you can replace the version with the other version if you want but make sure it's supported by this library.
5. Verify again your node run in x64 `node -p process.arch`
6. Reopen your terminal and try to install node-webrtc `npm i wrtc`

Please note this is make your nodejs will run in x64 arch, means you probably need to reinstall other modules in x64 arch if you previously install it in arch64.

**Comment by corwin-of-amber** [comment] 2021-10-20 19:50
Would it be possible to build a native version of node-webrtc for M1, without having to recompile WebRTC.Framework, based on https://github.com/stasel/WebRTC?

**Comment by corwin-of-amber** [comment] 2021-11-06 22:11
Update: I have been able to build wrtc.node on M1 (native). I will post my patches in my fork of node-webrtc.

Here is a binary in case anyone wants to test it.
[wrtc-bin.zip](https://github.com/node-webrtc/node-webrtc/files/7491314/wrtc-bin.zip)

**Comment by koush** [comment] 2021-11-09 07:57
> Update: I have been able to build wrtc.node on M1 (native). I will post my patches in my fork of node-webrtc.
> 
> Here is a binary in case anyone wants to test it. [wrtc-bin.zip](https://github.com/node-webrtc/node-webrtc/files/7491314/wrtc-bin.zip)

Do you mind posting your changes?

**Comment by koush** [comment] 2021-11-09 08:17
Ah found it. Testing. https://github.com/corwin-of-amber/node-webrtc.git

**Comment by corwin-of-amber** [comment] 2021-11-10 16:57
> Ah found it. Testing. https://github.com/corwin-of-amber/node-webrtc.git

Yes, sorry — I posted the link in #680, this should probably be marked as duplicate.
Make sure that you check out the `port/macos-arm64` branch:
https://github.com/corwin-of-amber/node-webrtc/tree/port/macos-arm64

**Comment by koush** [comment] 2021-11-10 17:50
I'm in the process of forking this project and creating builders, and I've rebuilt for every platform here:
https://github.com/koush/node-webrtc/releases/tag/0.4.9

However, I've noticed that the Mac x64 version fails to load:

```
Uncaught:
Error: dlopen(/private/tmp/work/node_modules/@koush/wrtc/build/Release/wrtc.node, 1): Symbol not found: __ZTTNSt3__119basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE
  Referenced from: /private/tmp/work/node_modules/@koush/wrtc/build/Release/wrtc.node
  Expected in: flat namespace
 in /private/tmp/work/node_modules/@koush/wrtc/build/Release/wrtc.node

```

The Mac x64 build was built on an x64 Mac (not M1). This issue does not occur on the M1 build (or windows or linux).

@corwin-of-amber Any idea why this may be?

**Comment by koush** [comment] 2021-11-11 06:15
I've tested this issue further. It seems to be a MacOS issue on Big Sur.

x64 build on Monterey: Works
x64 build on Big Sur: Does not work (symbol not found)

Building on Monterey or Big Sur host OS does not change the result.

**Comment by koush** [comment] 2021-11-11 22:34
Was due to missing object files not listed in libc++_objects. Specifically ios.instantiations.o. Unclear why this did not affect other builds.

https://github.com/koush/node-webrtc/commit/3dd9428a8e15c9eb1120cca1a090fa7c67d97925

**Comment by koush** [comment] 2021-11-11 23:13
Updated builds are available at `npm install @koush/wrtc`:
Linux x64, arm, arm64
Windows x64
Mac x64, arm64

**Comment by koush** [comment] 2021-11-12 00:00
> Was due to missing object files not listed in libc++_objects. Specifically ios.instantiations.o. Unclear why this did not affect other builds.
> 
> [koush@3dd9428](https://github.com/koush/node-webrtc/commit/3dd9428a8e15c9eb1120cca1a090fa7c67d97925)

I'm guessing this may be a late vs immediate lookup of symbols, and other platforms will similarly fail during actual execution without my patch.

**Comment by corwin-of-amber** [comment] 2021-11-12 11:46
Thanks @koush ! I removed `iostream.o` because it caused my build to crash, and had no idea why... it did seem weird to me that it crashed during static initialization; that can definitely be attributed to the missing `.o` files. Would never have figured it out.

I also removed libc++abi on macOS, should we put it back?

**Comment by corwin-of-amber** [comment] 2021-11-13 18:21
@koush Very nice work indeed. I wonder if there is a feasible way to distribute binaries of this package for different users using a multitude of Node versions. At least libwebrtc (the bulk of the work) is independent of the Node API version. Is it possible then to build several `.node` variants in one go without having to recompile libwebrtc every time?

Or, can the libwebrtc + libc++ binaries be distributed, such that users will be able to quickly compile compatible native versions?

Currently just the need to download ~10GB of Chromium sources is a showstopper for most users.

(too bad there is no issue feed for forks on GitHub; I am currently hijacking this thread.)

**Comment by koush** [comment] 2021-11-13 18:28
@corwin-of-amber I think the best way to do this would be to create libwebrtc build outputs as part of the release. Then the bindings can be build on any end user's desktop, for any node version, by downloading those build outputs. Decoupling the webrtc build from node-webrtc would also reduce future work, since this whole the webrtc checkout and build process is a huge pain.
That would also simplify matrix builds per node version.

**Comment by corwin-of-amber** [comment] 2021-11-13 20:46
That's exactly what I was thinking too. Good! I started working on separating the build into two phases. The first phase would be download libwebrtc sources, building with Ninja, and packaging the resulting object files (`.a`) and headers. The second phase would be unpacking the products of the first phase, and compiling the bindings with `ncmake` as is currently done.

The two phases can be decoupled nicely by uploading the results of the first phase.

**Comment by corwin-of-amber** [comment] 2021-11-14 21:24
Uhm I probably broke something because the Linux x86_64 version currently in `develop` crashes as soon as I try to create a `RTCPeerConnection`. This did not happen with the older version. The macOS version still works.

(This is not related to the two-phased build, which is in a separate branch for now.)

**Comment by koush** [comment] 2021-11-14 22:55
I don't think I've rebuilt Linux with the ios.instantiantion.o fix. Let me double check that and verify the builds.

**Comment by koush** [comment] 2021-11-15 03:30
Yes, also seeing a segmentation fault on Linux here with my fixes as well.

**Comment by koush** [comment] 2021-11-15 03:39
Confirmed that Windows and Mac are both working properly. Investigating the Linux issue.

**Comment by corwin-of-amber** [comment] 2021-11-15 09:17
It looks like maybe libwebrtc and wrtc.node somehow use different versions of `std::unique_ptr` despite the lengths CMakeLists.txt goes into to ensure consistent C++ headers.

In particular, this pointer is 0x8, despite being some other value when it was created in the callee:
https://github.com/koush/node-webrtc/blob/e5155e8e7a4420eb4bbf105369eebadd4c5df1ae/src/interfaces/rtc_peer_connection/peer_connection_factory.cc#L53

**Comment by koush** [comment] 2021-11-15 16:51
I briefly looked at this today, and at first glance the node-webrtc build does not seem to be including memory from external/libc++. I am guessing that other libc++ headers are being included erroneously.

**Comment by corwin-of-amber** [comment] 2021-11-15 18:34
I have inserted an `#error` directive in `memory` and it is in fact included by both libwebrtc and node-webrtc.

But I found a more alarming issue: libwebrtc compiles with clang++ and node-webrtc with g++ (`/usr/bin/c++`). This can't be right. I noticed that on Windows, `is_clang=false` is included in the build arguments. Perhaps this used to be the default in Linux but now isn't?..

**Comment by koush** [comment] 2021-11-15 19:47
> I have inserted an `#error` directive in `memory` and it is in fact included by both libwebrtc and node-webrtc.

Strange, that's the exact same thing I did, and was not getting an error.

**Comment by corwin-of-amber** [comment] 2021-11-15 20:34
Hmmmm very curious indeed.

Meanwhile, I did an experiment of building libwebrtc with g++. It works, but not with the bundled libc++. I had to set `use_custom_libcxx=false` (according to this: https://bugs.chromium.org/p/webrtc/issues/detail?id=7853). I used `-static-libstdc++` for linking wrtc.node and it loads and runs without crashing. Only question that remains is, is the world finally ready for "portable" C++ code. 😱 

The alternative would be to compile everything with the version of clang++ that's pulled by depot_tools, but this kind of defeats the purpose of simplifying the build for consumers of this package...

**Comment by koush** [comment] 2021-11-15 20:45
What is the build currently using on Linux? System C compiler? Or whatever is defined by CC?

**Comment by corwin-of-amber** [comment] 2021-11-15 21:05
Are you referring to the `wrtc.node` build? The CMakeLists.txt file does not specify. It selects `/usr/bin/c++`, which I assume is CMake's default.

libwebrtc's Ninja is using `download/src/third_party/llvm-build/Release+Asserts/bin/clang++`.

**Comment by koush** [comment] 2021-11-16 08:20
> Are you referring to the `wrtc.node` build? The CMakeLists.txt file does not specify. It selects `/usr/bin/c++`, which I assume is CMake's default.

Yeah, that is what I was talking about.

I'll take a look at your patches. Incidentally, I ran into the same ARM issues which uses what I think is gcc/g++

`wget https://releases.linaro.org/components/toolchain/binaries/7.3-2018.05/arm-linux-gnueabihf/gcc-linaro-7.3.1-2018.05-x86_64_arm-linux-gnueabihf.tar.xz`

It also did not work, but I was not using the the static/system libstdc++

**Comment by corwin-of-amber** [comment] 2021-11-18 23:01
I have prepared an experimental phased build setup at https://github.com/corwin-of-amber/node-webrtc/tree/wip/phased-build. It is not yet fully automatic and definitely begs to be cleaned up. Preliminary testing on Linux x64, macOS x64, and macOS arm64 are encouraging and I have deployed binaries at https://github.com/corwin-of-amber/node-webrtc/releases.

I have been able to build the Linux arm and arm64 versions of libwebrtc, but the CMakeLists.txt expects an environment variable `ARM_TOOLS_PATH`, which I guess should be pointed to an installation of the tarball you referenced there. I haven't tried it yet, mostly because I have no idea how to even test the cross-compiled binaries.

**Comment by corwin-of-amber** [comment] 2021-11-18 23:07
Oh and needless to say, Windows build is TBD. I have introduced two shell scripts `pack-webrtc.sh` and `unpack-webrtc.sh` which depend on `ar` and `tar` so are very much *nix-specific. I am considering translating them to JS for easier maintenance.

**Comment by koush** [comment] 2021-11-19 00:28
> I haven't tried it yet, mostly because I have no idea how to even test the cross-compiled binaries.

I can verify. My primary use case is arm. Testable on Raspberry pi.

Does this change have the necessary adjustments to use gcc instead of clang as you mentioned?

**Comment by koush** [comment] 2021-11-19 03:25
The libraries are quite large: do they have debug symbols or something? 100mb each. Can those be stripped?

**Comment by corwin-of-amber** [comment] 2021-11-19 13:35
Hi! Yes, the Linux x64 build uses g++ as it turned out to be quite impossible to use clang in the phased build.

The libwebrtc binaries are unfortunately large because they contain everything: all of the object files from libwebrtc as well as peerconnection and libc++. You can see that the Linux 64 one is much smaller. The default build is Release, so they should not have debug symbols as far as I can tell. But I may not fully understand the implications of the CMake config.

The wrtc libs are much smaller and are the only libs that you need to deploy to your devices. They contain exactly the objects that are needed by the bindings, as the linker throws away everything else.

I assume you can build Linux arm binaries that also use g++ instead of clang. Currently I left it as it was, so only the Linux x64 is using g++ with system libstdc++, and the rest use the custom libc++.

So the plan is going to be: if binary-compatible bindings are available, the user's download is going to be ~10MB. If platform binaries exist but the NAPI version is incompatible, the user will download ~100MB depending on platform of libwebrtc binaries and compile the bindings locally. On a platform for which no binaries not included in the release, the user will have to download the whole ~10GB of Chromium libwebrtc dependencies as before.

Notice that NAPI v3 is in fact supported across a range of Node versions. So the first use case becomes more likely now that we make use of that.

**Comment by corwin-of-amber** [comment] 2021-11-19 14:42
Uhm some weird thing happens: if I run `TARGET_ARCH=arm npm run build` in `phase-1`, it dies when downloading the sources, with:
```
Error: 1> Could not switch upstream branch from refs/remotes/origin/main to refs/remotes/branch-heads/4707
```
If I run `npm run build`, Ctrl-C it, then run `TARGET_ARCH=arm npm run build`, it downloads ok...
I don't see that `TARGET_ARCH` even affects depot_tools... what is going on here?

**Comment by upendratunity** [comment] 2021-11-20 08:19
> Following the [guideline here ](https://www.jurnalanas.com/node-js-mac-m1/) i managed to install this on Macbook Air M1. I'm using [NVM](https://github.com/nvm-sh/nvm) to install my node.
> 
> 1. Open terminal
> 2. switch to x64 arch `arch -x86_64 zsh`, change `zsh` with your own shell
> 3. make sure you run in x64 arch by run `node -p process.arch` it must be output `x64` if everything correct
> 4. Install node in x65 version `nvm install v14.15.4`, you can replace the version with the other version if you want but make sure it's supported by this library.
> 5. Verify again your node run in x64 `node -p process.arch`
> 6. Reopen your terminal and try to install node-webrtc `npm i wrtc`
> 
> Please note this is make your nodejs will run in x64 arch, means you probably need to reinstall other modules in x64 arch if you previously install it in arch64.

Thanks it worked.

**Comment by corwin-of-amber** [comment] 2021-11-20 14:10
Ok it does not happen anymore. I think I was just using an intermediate version of CMakeLists.txt by mistake. I have uploaded phase-1 binaries for arm. At least I think I have: the archives are smaller than the x64 ones even though they contain libc++.a as well... so probably something is missing.

**Comment by koush** [comment] 2021-11-20 22:02
> I don't see that TARGET_ARCH even affects depot_tools... what is going on here?

It is used by the node-webrtc scripts only, as far as I can tell; not directly by libwebrtc. That and ARM_TOOLS_PATH set up the libwebrtc environment. Sets up sysroots and whatnot.
 
> Hi! Yes, the Linux x64 build uses g++ as it turned out to be quite impossible to use clang in the phased build.
> I assume you can build Linux arm binaries that also use g++ instead of clang. Currently I left it as it was, so only the Linux x64 is using g++ with system libstdc++, and the rest use the custom libc++.

I'm going to try to get the matrix phased prebuilts set up this weekend. Just so I understand how things work now with your phased build, here are my assumptions on how things worked before and after:

Before:
libwebrtc build previously/default used a clang toolchain that came with depot_tools

After:
Your phased change now disables usage of this included clang with `use_custom_libcxx=false` and `-static-libstdc++`.
This change assumes g++ is available in PATH. Or presumably the ARM_TOOLS_PATH binary.

**Comment by corwin-of-amber** [comment] 2021-11-21 20:18
Yes, almost: I use the system compiler on Linux x64; when cross-compiling for ARM, I left the old behavior that uses the bundled clang and libc++. I've done this for two reasons:
* I was too worried that it would break because I do not currently have a test setup for Linux ARM.
* I assumed (perhaps wrongly, feel free to correct me) that one will be *cross-compiling* for e.g. Raspberry Pi, rather than compiling on the device itself. In that use case they would not benefit much from the phased build; although they might still benefit from having the precompiled binaries.

Actually I was wondering how it used to work in the past, because libwebrtc was compiled using the bundled clang, but wrtc.node was compiled and linked via ARM_TOOLS_PATH and gcc/c++. Are those supposed to be ABI-compatible? Because, as my previous experience with Linux x64 shows, at least clang++ and Debian 10's default g++ are not.

**Comment by corwin-of-amber** [comment] 2021-11-21 20:20
BTW we have gone a bit beyond the title of this current issue thread to discuss the build in general. Should we create a PR instead, and continue the discussion there?

**Comment by koush** [comment] 2021-11-21 22:28
Yes, it is a cross compile, and not an on device compile.
Linux arm and arm64 were failing similarly to x64. How did you prevent libwebrtc from using the included toolchain on linux x64? That wasn't with `use_custom_libcxx=false` doesn't sound like it would do it.

**Comment by corwin-of-amber** [comment] 2021-11-22 08:30
It's `use_clang=false`.

**Comment by matej-io** [comment] 2021-11-22 17:45
> Update: I have been able to build wrtc.node on M1 (native). I will post my patches in my fork of node-webrtc.
> 
> Here is a binary in case anyone wants to test it. [wrtc-bin.zip](https://github.com/node-webrtc/node-webrtc/files/7491314/wrtc-bin.zip)

This worked for me, I just replaced `wrtc.node` inside `node_modules/wrtc/build/Release` in my project.

**Comment by corwin-of-amber** [comment] 2021-11-22 18:53
Thanks @matejukmar. That's encouraging to know! Can you try the newer, less hacky version from https://github.com/corwin-of-amber/node-webrtc/releases?

**Comment by SergiyMolchan** [comment] 2021-12-31 16:45
Set by specifying the flag --target_arch for example: npm i wrtc --target_arch=x64

**Comment by thisisamir98** [comment] 2022-02-25 14:10
Downgrading Node.js from 16.5.0 to 14.17.6 fixed it for me.

**Comment by compojoom** [comment] 2022-06-21 09:20
@corwin-of-amber @koush - I see that you guys have forks that fix the issue at hand. Do you think it would be worth it to create a PR to this repo? I was able to replace a wrtc dependency with `"@koush/wrtc": "^0.5.3",` and installing on M1 went fine. 

Or do you think that this repo is missing a maintainer?

**Comment by koush** [comment] 2022-06-21 15:44
The @koush/wrtc fork has an issue where extracting the stream source fails. That's when I stopped bothering trying to fix issues with it. I felt I was constantly fighting with Google's technical debt. I think the google webrtc implementation is a giant mess and far too difficult to maintain and extend. There are now better options including werift and node-datachannel.

I'm an active contributor to https://github.com/shinyoshiaki/werift-webrtc, and it's completely replaced wrtc within my various projects. It's pure typescript and has a superior set of features that are unavailable in Google's implementation (which tightly couples the encoder/decoder to the webrtc implementation).

**Comment by corwin-of-amber** [comment] 2022-06-23 19:21
I completely agree with @koush. Besides the original maintainer seemingly having abandoned it, it is a total headache to maintain due to its reliance on the Chromium build setup. Personally, I am still using `@koush/wrtc` in my project and it works great for me, but I have plans to take the above advice and switch to werift.

**Comment by dmitryame** [comment] 2022-07-10 23:39
sorry, newby here, what exactly do I have to do to make it work in my project?

**Comment by corwin-of-amber** [comment] 2022-07-19 08:39
Just use `npm i @koush/wrtc` and replace all your `import ... from 'wrtc'` with `import ... from '@koush/wrtc'`.

Also you can try the examples on the werift repo, notice that their API might be a bit different though.

**Comment by azabrodin** [comment] 2023-09-09 10:19
macOS Ventura 13.5.2. M1. Doesn’t work anything! 
Can't install WRTC! 
It works before with node 14.15.4, but doesn’t work now! Please help!

**Comment by duvallj** [comment] 2024-05-01 22:53
See https://github.com/node-webrtc/node-webrtc/pull/766

**Closed as completed by duvallj** 2024-05-01 22:53 UTC
